const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={speed:60,safety:75,goal:80,crash:70,step:1,elapsed:0,paused:false,session:1200,raf:0};
const keys=['speed','safety','goal','crash'],presets={speed:[95,25,70,25],safe:[35,100,75,100],balance:[60,75,80,70]};
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function grade(v){return v>82?'S':v>68?'A':v>48?'B':'C'}
function rewards(){keys.forEach(k=>{let e=$('#'+k),v=+e.value;S[k]=v;e.style.setProperty('--fill',v+'%');$('#'+k+'O').textContent=(k==='crash'?'−':'+')+v});personality();radar()}
function personality(){let n,c,t;if(S.speed>80&&S.safety<50){n='ワイルド・エクスプローラー';c='未知の行動を次々試すよ。でも探索しすぎると覚えられないかも。';t='WILD EXPLORER'}else if(S.safety>85&&S.speed<55){n='ローカル・クライマー';c='少しでもゴールへ近づく行動を重視するよ。途中で満足しないよう注意！';t='LOCAL CLIMBER'}else if(S.goal<35){n='好奇心旺盛な探検家';c='ゴールだけが答えじゃない。まだ見ぬルートを探してみたい！';t='CURIOUS EXPLORER'}else{n='スマート・ナビゲーター';c='探索と報酬のバランスを取りながら、本当にゴールできる方策を探すよ！';t='SMART NAVIGATOR'}$('#pname').textContent=n;$('#comment').textContent=c;$('#btype').textContent=t;$('#g1').textContent=grade((S.goal+S.safety)/2);$('#g2').textContent=grade(S.speed-S.crash*.2+30);$('#g3').textContent=grade((S.safety+S.crash)/2)}
function radar(){let c=$('#radar'),x=c.getContext('2d'),cx=240,cy=155,R=103,v=[S.speed,S.goal,S.safety,S.crash,(S.goal+S.speed)/2],names=['探索幅','ゴール','接近報酬','衝突罰','バランス'];x.clearRect(0,0,480,300);for(let r=1;r<=4;r++){x.beginPath();for(let i=0;i<5;i++){let a=-Math.PI/2+i*Math.PI*2/5,q=R*r/4;x[i?'lineTo':'moveTo'](cx+Math.cos(a)*q,cy+Math.sin(a)*q)}x.closePath();x.strokeStyle='#294354';x.stroke()}for(let i=0;i<5;i++){let a=-Math.PI/2+i*Math.PI*2/5;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='#1c3546';x.stroke();x.fillStyle='#7890a2';x.font='11px sans-serif';x.textAlign=i===0?'center':i<3?'left':'right';x.fillText(names[i],cx+Math.cos(a)*(R+22),cy+Math.sin(a)*(R+15))}x.beginPath();v.forEach((q,i)=>{let a=-Math.PI/2+i*Math.PI*2/5,q2=R*q/100;x[i?'lineTo':'moveTo'](cx+Math.cos(a)*q2,cy+Math.sin(a)*q2)});x.closePath();x.fillStyle='#18d9dc33';x.fill();x.strokeStyle='#18d9dc';x.lineWidth=2;x.stroke()}
function go(n){document.body.classList.toggle('training-focus',n===2);S.step=Math.max(S.step,n);$$('.panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===n));$$('.step').forEach(b=>b.classList.toggle('active',+b.dataset.step===n));scrollTo({top:0,behavior:'smooth'});if(n===2)startTraining()}
keys.forEach(k=>$('#'+k).oninput=()=>{$$('[data-preset]').forEach(b=>b.classList.remove('on'));rewards()});$$('[data-preset]').forEach(b=>b.onclick=()=>{presets[b.dataset.preset].forEach((v,i)=>$('#'+keys[i]).value=v);$$('[data-preset]').forEach(q=>q.classList.toggle('on',q===b));rewards()});
$('#reset').onclick=()=>{$('[data-preset=balance]').click();toast('初期設定に戻しました')};$('#start').onclick=()=>{$('#hero').classList.add('hidden');$('#app').classList.remove('hidden');radar()};$('#train').onclick=()=>go(2);$('#transfer').onclick=()=>go(3);$$('.step').forEach(b=>b.onclick=()=>{if(+b.dataset.step<=S.step)go(+b.dataset.step)});$('#sound').onclick=()=>toast('サウンドを切り替えました');
setInterval(()=>{if(!$('#app').classList.contains('hidden')&&S.session){S.session--;$('#time').textContent=`${String(S.session/60|0).padStart(2,'0')}:${String(S.session%60).padStart(2,'0')}`}},1000);
const sim=$("#sim"),ctx=sim.getContext("2d"),layouts={standard:[{x:270,y:125,r:34},{x:455,y:350,r:42},{x:650,y:170,r:38},{x:710,y:390,r:26}],slalom:[{x:260,y:315,r:35},{x:420,y:175,r:38},{x:580,y:330,r:38},{x:720,y:165,r:32}],gate:[{x:345,y:215,r:42},{x:345,y:360,r:42},{x:610,y:100,r:38},{x:610,y:250,r:38}]};let obs=layouts.standard,currentLayout="A",last=0,episode=-1,event={type:"",age:9,x:0,y:0};
// Change only this profile when moving between the bundled A4 mat and a large mat.
// The A4 profile rotates raw Position ID coordinates to match a landscape screen.
const MAT_PROFILES={
  a4:{name:"A4 SIMPLE MAT / LANDSCAPE",xMin:98,xMax:402,yMin:142,yMax:358,rotation:"cw",inset:28},
  large:{name:"LARGE PLAY MAT",xMin:45,xMax:455,yMin:45,yMax:455}
};
const MAT_PROFILE=MAT_PROFILES.a4;
const MAT_SCALE=Math.min((MAT_PROFILE.xMax-MAT_PROFILE.xMin)/sim.width,(MAT_PROFILE.yMax-MAT_PROFILE.yMin)/sim.height);
const MAT_OFFSET={
  x:MAT_PROFILE.xMin+((MAT_PROFILE.xMax-MAT_PROFILE.xMin)-sim.width*MAT_SCALE)/2,
  y:MAT_PROFILE.yMin+((MAT_PROFILE.yMax-MAT_PROFILE.yMin)-sim.height*MAT_SCALE)/2
};
function activeMatBounds(){let inset=MAT_PROFILE.inset||0;return{xMin:MAT_PROFILE.xMin+inset,xMax:MAT_PROFILE.xMax-inset,yMin:MAT_PROFILE.yMin+inset,yMax:MAT_PROFILE.yMax-inset}}
function simToMat(x,y){if(MAT_PROFILE.rotation==="cw"){let b=activeMatBounds();return{x:b.xMin+y/sim.height*(b.xMax-b.xMin),y:b.yMax-x/sim.width*(b.yMax-b.yMin)}}return{x:MAT_OFFSET.x+x*MAT_SCALE,y:MAT_OFFSET.y+y*MAT_SCALE}}
function matToSim(x,y){if(MAT_PROFILE.rotation==="cw"){let b=activeMatBounds();return{x:(b.yMax-y)/(b.yMax-b.yMin)*sim.width,y:(x-b.xMin)/(b.xMax-b.xMin)*sim.height}}return{x:(x-MAT_OFFSET.x)/MAT_SCALE,y:(y-MAT_OFFSET.y)/MAT_SCALE}}
function matAngleToSim(angle){let corrected=MAT_PROFILE.rotation==="cw"?angle+90:angle;return corrected*Math.PI/180}
function isInsideRealCourse(p){return p.x>=35&&p.x<=865&&p.y>=30&&p.y<=490}
function grid(){ctx.fillStyle='#07141f';ctx.fillRect(0,0,900,520);ctx.strokeStyle='#153044';for(let q=0;q<900;q+=45){ctx.beginPath();ctx.moveTo(q,0);ctx.lineTo(q,520);ctx.stroke()}for(let q=0;q<520;q+=45){ctx.beginPath();ctx.moveTo(0,q);ctx.lineTo(900,q);ctx.stroke()}ctx.setLineDash([5,7]);ctx.strokeStyle='#2a475a';ctx.strokeRect(32,28,836,464);ctx.setLineDash([]);ctx.fillStyle="#7890a2";ctx.font="bold 13px Inter,sans-serif";ctx.textAlign="right";ctx.fillText(`COURSE ${currentLayout} · TOIO MAT COORDINATES`,850,505);ctx.textAlign="center"}
function quality(){return Math.max(.08,Math.min(1,(100-Math.abs(S.speed-60)*.8-Math.abs(S.safety-78)*.65-Math.abs(S.goal-85)*.55-Math.abs(S.crash-78)*.5)/100))}
function outcome(ep,learn){let random=Math.abs(Math.sin(ep*12.9898)*43758.5453)%1,maturity=Math.max(0,(learn-.45)/.55),goalDrive=.25+S.goal/135,chance=Math.min(.9,maturity*quality()*goalDrive*1.2);if(random<chance)return "goal";let avoidance=learn*(S.safety*.55+S.crash*.45)/100,crashChance=.74-avoidance*.58;return random<crashChance?"crash":"timeout"}
function stats(currentEp){let start=Math.max(0,currentEp-9),goals=0,crashes=0,total=currentEp-start+1;for(let ep=start;ep<=currentEp;ep++){let result=outcome(ep,Math.min(1,ep*.65/15));if(result==="goal")goals++;if(result==="crash")crashes++}let allCrashes=0;for(let ep=0;ep<=currentEp;ep++)if(outcome(ep,Math.min(1,ep*.65/15))==="crash")allCrashes++;return{rate:Math.round(goals/total*100),crashes:allCrashes}}
function curve(a,b,c,d,t){let u=1-t;return u*u*u*a+3*u*u*t*b+3*u*t*t*c+t*t*t*d}
function safePoint(p){let routes={A:[[65,390],[190,420],[370,270],[540,75],[825,90]],B:[[65,390],[180,470],[500,470],[820,470],[860,250],[825,90]],C:[[65,390],[180,470],[470,470],[800,455],[860,260],[825,90]]},points=routes[currentLayout],scaled=p*(points.length-1),i=Math.min(points.length-2,Math.floor(scaled)),u=scaled-i,u2=u*u*(3-2*u),a=points[i],b=points[i+1];return{x:a[0]+(b[0]-a[0])*u2,y:a[1]+(b[1]-a[1])*u2}}
function bot(t){let ep=Math.floor(t/.65),phase=(t%.65)/.65,learn=Math.min(1,t/15),result=outcome(ep,learn),endAt=.88-S.speed*.0018,p=Math.min(phase/endAt,1),seed=Math.abs(Math.sin(ep*17.13)),turn=seed>.5?1:-1,x,y,tx,ty,c1x,c1y,c2x,c2y;if(result==="crash"){let o=obs[ep%obs.length];tx=o.x;ty=o.y;c1x=120+seed*180;c1y=390+turn*(90+seed*80);c2x=o.x-130;c2y=o.y-turn*(70+seed*40)}else if(result==="timeout"){let a=-2.8+(Math.abs(Math.sin(ep*7.31))%1)*3.7,d=200+(ep%5)*48;tx=Math.max(60,Math.min(840,65+Math.cos(a)*d));ty=Math.max(50,Math.min(470,390+Math.sin(a)*d));c1x=120+seed*190;c1y=390+turn*150;c2x=tx-100;c2y=ty-turn*130}else{tx=825;ty=90}if(result==="goal"){let safe=safePoint(p);x=safe.x;y=safe.y}else{x=curve(65,c1x,c2x,tx,p);y=curve(390,c1y,c2y,ty,p)};let explore=(1-learn*quality())*(35+S.speed*.25)*(1-S.safety/180),wave=Math.sin(p*Math.PI)*Math.sin(p*22+ep*2.1)*explore;y+=wave;x+=Math.sin(p*Math.PI)*Math.cos(p*15+ep)*explore*.45;return{x,y,ep,phase,result,learn,explore,tx,ty,endAt}}
function drawMemory(r,q){let learned=Math.min(1,r*q*1.8);if(learned>.12)obs.forEach((o,i)=>{let a=Math.max(0,Math.min(.55,(learned-i*.12)*.7));if(a<=0)return;ctx.beginPath();ctx.arc(o.x,o.y,o.r+18+learned*12,0,7);ctx.fillStyle=`rgba(255,84,117,${a*.18})`;ctx.fill();ctx.setLineDash([3,5]);ctx.strokeStyle=`rgba(255,84,117,${a})`;ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=`rgba(255,150,170,${a})`;ctx.font="7px Inter,sans-serif";ctx.fillText("DANGER MEMORY",o.x,o.y-o.r-25)});if(learned>.55){ctx.beginPath();for(let i=0;i<=30;i++){let u=i/30,safe=safePoint(u);ctx[i?"lineTo":"moveTo"](safe.x,safe.y)}ctx.strokeStyle=`rgba(73,242,165,${(learned-.55)*1.4})`;ctx.lineWidth=8;ctx.shadowColor="#49f2a5";ctx.shadowBlur=12;ctx.stroke();ctx.shadowBlur=0;ctx.lineWidth=1;ctx.fillStyle="#49f2a5";ctx.font="bold 8px Inter,sans-serif";ctx.fillText("LEARNED SAFE POLICY",585,58)}}
function drawNetwork(progress,q){let c=$("#network");if(!c)return;let x=c.getContext("2d"),layers=[6,8,2],xs=[22,115,208],positions=layers.map((count,l)=>Array.from({length:count},(_,i)=>({x:xs[l],y:13+(i+1)*99/(count+1)})));x.clearRect(0,0,c.width,c.height);for(let l=0;l<2;l++)positions[l].forEach((a,i)=>positions[l+1].forEach((b,j)=>{let seed=Math.sin((l+1)*97+i*17+j*31),learned=Math.sin(i*1.7-j*2.1+l)*q,weight=seed*(1-progress)+learned*progress;x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.strokeStyle=weight>=0?`rgba(24,217,220,${.08+Math.abs(weight)*.72})`:`rgba(255,84,117,${.08+Math.abs(weight)*.72})`;x.lineWidth=.4+Math.abs(weight)*2;x.stroke()}));positions.forEach((layer,l)=>layer.forEach((n,i)=>{x.beginPath();x.arc(n.x,n.y,l===1?3.2:4,0,7);x.fillStyle=l===0?"#8465ff":l===1?"#d8f8ff":"#49f2a5";x.fill();x.strokeStyle="#07141f";x.stroke()}));x.fillStyle="#617b8d";x.font="6px Inter,sans-serif";x.textAlign="center";x.fillText("STATE ×6",22,121);x.fillText("HIDDEN ×8",115,121);x.fillText("MOTOR ×2",208,121)}
function chart(r){let c=$("#chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle="#183244";for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,i*h/4);x.lineTo(w,i*h/4);x.stroke()}x.beginPath();for(let i=0;i<=100*r;i++){let px=i/100*w,py=h-15-i/100*(h-30)+Math.sin(i*.5)*7*(1-i/120);x[i?"lineTo":"moveTo"](px,py)}x.strokeStyle="#18d9dc";x.lineWidth=3;x.stroke()}
function drawThinking(p){let sensor=34+S.safety*.62,detected=false;ctx.save();ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(p.x,p.y,sensor,0,7);ctx.strokeStyle=`rgba(73,242,165,${.18+S.safety/500})`;ctx.stroke();ctx.setLineDash([]);obs.forEach(o=>{let d=Math.hypot(o.x-p.x,o.y-p.y);if(d<sensor+o.r){detected=true;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(o.x,o.y);ctx.strokeStyle="#ff8b4899";ctx.lineWidth=2;ctx.stroke()}});let ga=(S.goal/100)*.8,ang=Math.atan2(90-p.y,825-p.x);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.cos(ang)*(32+S.goal*.35),p.y+Math.sin(ang)*(32+S.goal*.35));ctx.strokeStyle=`rgba(132,101,255,${ga})`;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#07141fdd";ctx.fillRect(42,35,240,92);ctx.strokeStyle="#29485a";ctx.strokeRect(42,35,240,92);ctx.fillStyle="#6f899b";ctx.font="8px Inter,sans-serif";ctx.fillText("AI IS THINKING / 現在の判断",57,53);ctx.fillStyle=detected?"#ffb077":"#e9f8ff";ctx.font="bold 12px sans-serif";let thought=detected?"障害物を検知 → 回避を計算":p.result==="goal"?"学習した安全経路を追跡":"未知の方向をランダム探索中…";ctx.fillText(thought,57,73);ctx.font="9px sans-serif";ctx.fillStyle="#18d9dc";ctx.fillText(`速度 ${S.speed}%`,57,94);ctx.fillStyle="#49f2a5";ctx.fillText(`検知範囲 ${Math.round(sensor)}`,119,94);ctx.fillStyle="#8465ff";ctx.fillText(`ゴール意識 ${S.goal}%`,57,112);ctx.fillStyle="#ff8b48";ctx.fillText(`衝突警戒 ${S.crash}%`,145,112);ctx.restore()}
function drawGhosts(t){for(let i=1;i<=18;i++){let g=bot(Math.max(0,t-i*.037));if(g.phase>g.endAt)continue;ctx.beginPath();ctx.arc(g.x,g.y,5,0,7);ctx.fillStyle=g.result==="goal"?"#49f2a555":g.result==="crash"?"#ff547538":"#ffd16638";ctx.fill()}}
function burst(x,y,color,age){for(let i=0;i<14;i++){let a=i/14*Math.PI*2,d=age*90;ctx.beginPath();ctx.arc(x+Math.cos(a)*d,y+Math.sin(a)*d,Math.max(1,5-age*5),0,7);ctx.fillStyle=color;ctx.globalAlpha=Math.max(0,1-age);ctx.fill()}ctx.globalAlpha=1}
function setLayout(name,button){obs=layouts[name];currentLayout=button.textContent;document.querySelectorAll("[data-layout]").forEach(b=>b.classList.toggle("layout-on",b===button));toast(`コース ${currentLayout} に変更 — AIの記憶をリセット`);startTraining()}
function verdict(type,age){let goal=type==="goal",timeout=type==="timeout",color=goal?"#49f2a5":timeout?"#ffd166":"#ff5475",label=goal?"GOAL! +100":timeout?"TIME UP −20":"CRASH! −70";ctx.fillStyle="#06111ccc";ctx.fillRect(285,205,330,88);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(285,205,330,88);ctx.fillStyle=color;ctx.font="800 25px Inter,sans-serif";ctx.textAlign="center";ctx.fillText(label,450,243);ctx.fillStyle="#a9bac7";ctx.font="10px sans-serif";ctx.fillText(goal?"新しい安全ルートを記憶しました":timeout?"ゴールまでの距離を報酬へ反映":"この経路を避けるよう学習します",450,268);burst(event.x,event.y,color,age)}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!S.paused)S.elapsed=Math.min(15,S.elapsed+dt);S.raf=requestAnimationFrame(frame);grid();drawMemory(S.elapsed/15,quality());drawNetwork(S.elapsed/15,quality());ctx.beginPath();ctx.arc(825,90,35,0,7);ctx.fillStyle="#8465ff33";ctx.fill();ctx.strokeStyle="#8d70ff";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#c7bbff";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText("GOAL",825,95);obs.forEach(o=>{ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fillStyle="#ff8b4828";ctx.fill();ctx.strokeStyle="#ff8b48";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#ffb17f";ctx.font="9px sans-serif";let oi=obs.indexOf(o),mx=Math.round(45+o.x/900*410),my=Math.round(45+o.y/520*410);ctx.fillText(`O${oi+1}`,o.x,o.y+3);ctx.fillStyle="#9aabbb";ctx.font="7px Inter,sans-serif";ctx.fillText(`(${mx}, ${my})`,o.x,o.y+o.r+13)});let p=bot(S.elapsed);drawGhosts(S.elapsed);drawThinking(p);ctx.setLineDash([4,6]);ctx.beginPath();for(let i=0;i<=20;i++){let h=bot(p.ep*.65+p.phase*.65*i/20);ctx[i?"lineTo":"moveTo"](h.x,h.y)}ctx.strokeStyle="#18d9dc66";ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(p.x,p.y,11,0,7);ctx.fillStyle="#18d9dc";ctx.shadowColor="#18d9dc";ctx.shadowBlur=15;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle="#d5ffff";ctx.lineWidth=3;ctx.stroke();if(p.ep!==episode){episode=p.ep;event={type:p.result,age:9,x:p.x,y:p.y}}if(p.phase>p.endAt){event.x=p.x;event.y=p.y;event.age=Math.max(0,Math.min(1,(p.phase-p.endAt)/(1-p.endAt)));verdict(p.result,event.age)}let r=S.elapsed/15,q=quality(),tr=Math.floor(r*r*30000),st=stats(p.ep),rate=st.rate,cr=st.crashes,rw=Math.round(-35+r*q*135),logs=q<.45?["報酬の手がかりを探索中…","速度を上げすぎて衝突が増加","同じ失敗経路を選んでいます","安全報酬が不足しています","まだ方策が安定しません","パラメータ調整が必要です","学習終了 — 成功率が伸びませんでした"]:["18体を並列にランダム探索中…","衝突した座標を危険として記憶","失敗経路の選択確率を低下","安全な経路候補を発見！","速度と回避のバランスを調整","成功する経路が増えています","方策が安定しました ✓"];$("#count").textContent=(15-S.elapsed).toFixed(1);$("#trials").textContent=tr.toLocaleString();$("#success").textContent=rate+"%";$("#crashes").textContent=cr.toLocaleString();$("#ring").style.background=`conic-gradient(var(--cyan) ${r*100}%,#1b3243 0)`;$("#reward").textContent=(rw>0?"+":"")+rw;$("#log").textContent=logs[Math.min(6,Math.floor(r*7))];let intel=Math.min(5,Math.floor(r*q*6)),stages=["探索を開始","失敗を記憶中","危険を予測中","回避行動を習得","経路を最適化","方策が完成！"];$("#intelLevel").textContent=intel;$("#intelBar").style.width=(r*q*100)+"%";$("#intelStage").textContent=stages[intel];$("#dangerCount").textContent=Math.min(4,Math.floor(r*q*7));$("#ruleCount").textContent=Math.floor(r*q*12);chart(r*q);if(S.elapsed>=15){cancelAnimationFrame(S.raf);$("#transfer").classList.remove("hidden");S.step=3;toast(q>.65?"失敗から学び、AIが賢くなりました！":"学習完了。報酬を見直すともっと賢くなります");return}}
function startTraining(){cancelAnimationFrame(S.raf);S.elapsed=0;S.paused=false;episode=-1;event={type:"",age:9,x:0,y:0};$("#transfer").classList.add("hidden");last=performance.now();S.raf=requestAnimationFrame(frame)}$("#pause").onclick=()=>{S.paused=!S.paused;$("#pause").textContent=S.paused?"▶":"Ⅱ"};$("#retry").onclick=startTraining;document.querySelectorAll("[data-layout]").forEach(b=>b.onclick=()=>setLayout(b.dataset.layout,b));

// toio BLE: official service, ID sensor and motor characteristics.
const TOIO_SERVICE='10b20100-5b3b-4571-9508-cf3efcd7bbae',ID_CHAR='10b20101-5b3b-4571-9508-cf3efcd7bbae',MOTOR_CHAR='10b20102-5b3b-4571-9508-cf3efcd7bbae',LIGHT_CHAR='10b20103-5b3b-4571-9508-cf3efcd7bbae',CONFIG_CHAR='10b201ff-5b3b-4571-9508-cf3efcd7bbae';let cube=null,motor=null,idSensor=null,light=null,configuration=null,policyTimer=null,lastPose=null,lastCommand={left:0,right:0},avoidance={index:-1,side:0};
async function stopCube(){if(motor)await motor.writeValueWithoutResponse(Uint8Array.of(1,1,1,0,2,1,0)).catch(()=>{})}
async function setCubeLight(red,green,blue,duration=100){if(!light)return;let data=Uint8Array.of(0x03,duration,0x01,0x01,red,green,blue);try{if(light.writeValueWithResponse)await light.writeValueWithResponse(data);else await light.writeValue(data)}catch(_){}}
async function clearCubeLight(){if(!light)return;let data=Uint8Array.of(0x01);try{if(light.writeValueWithResponse)await light.writeValueWithResponse(data);else await light.writeValue(data)}catch(_){}}
// 30 = 300 ms. The 100 ms control loop refreshes it; loss of communication stops the cube automatically.
const REAL_SPEED_SCALE=.6,REAL_MIN_SPEED=12,REAL_MAX_SPEED=45;
const telemetryQueue=[];
function recordTelemetry(data){let entry={time:new Date().toISOString(),...data};telemetryQueue.push(entry);let live=$("#telemetryLive"),labels={RUNNING:"走行中",GOAL_REACHED:"ゴール！",COURSE_EDGE:"場外停止",MAT_LOST:"マットを見失いました",POSITION_TIMEOUT:"位置情報停止"};if(live){live.textContent=`${labels[entry.status]||entry.status}  P:${entry.x??"-"},${entry.y??"-"}  A:${entry.angle??"-"}°  TURN:${entry.turn??"-"}°  L:${entry.left??"-"}  R:${entry.right??"-"}`;live.parentElement.classList.toggle("goal",entry.status==="GOAL_REACHED")}}
async function flushTelemetry(){if(!telemetryQueue.length)return;let batch=telemetryQueue.splice(0,telemetryQueue.length);try{let response=await fetch("/telemetry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(batch)});if(!response.ok)throw new Error(String(response.status))}catch(_){telemetryQueue.unshift(...batch.slice(-100))}}
setInterval(flushTelemetry,1000);
function scaleRealMotor(value){if(!value)return 0;let scaled=Math.round(value*REAL_SPEED_SCALE),direction=Math.sign(scaled||value);return direction*Math.max(REAL_MIN_SPEED,Math.min(REAL_MAX_SPEED,Math.abs(scaled)))}
function drive(left,right,duration=30){if(!motor)return;let ld=left>=0?1:2,rd=right>=0?1:2;motor.writeValueWithoutResponse(Uint8Array.of(2,1,ld,Math.abs(left),2,rd,Math.abs(right),duration)).catch(()=>{})}
function onPosition(e){let d=e.target.value,type=d.byteLength?d.getUint8(0):0;if(type===3){lastPose=null;lastCommand={left:0,right:0};stopCube();clearCubeLight();$("#deviceState").textContent="MAT LOST / STOPPED";recordTelemetry({status:"MAT_LOST"});return}if(d.byteLength<7||type!==1)return;lastPose={x:d.getUint16(1,true),y:d.getUint16(3,true),a:d.getUint16(5,true),at:performance.now()}}
function guidedMotors(agent,learned){let goalAngle=Math.atan2(window.realTrainer.goal.y-agent.y,window.realTrainer.goal.x-agent.x),goalError=window.realTrainer.wrap(goalAngle-agent.angle),obstacles=window.realTrainer.obstacles,states=obstacles.map((obstacle,index)=>{let dx=obstacle.x-agent.x,dy=obstacle.y-agent.y;return{index,clearance:Math.hypot(dx,dy)-obstacle.r-10,relative:window.realTrainer.wrap(Math.atan2(dy,dx)-agent.angle)}});if(avoidance.index>=0){let state=states[avoidance.index];if(!state||state.clearance>205||Math.abs(state.relative)>1.75)avoidance={index:-1,side:0}}if(avoidance.index<0){let threats=states.filter(state=>state.clearance<165&&Math.abs(state.relative)<1.15).sort((a,b)=>a.clearance-b.clearance);if(threats.length){let threat=threats[0];avoidance={index:threat.index,side:threat.relative>=0?-1:1}}}let avoid=0,nearest=Infinity;if(avoidance.index>=0){let state=states[avoidance.index];nearest=state.clearance;avoid=avoidance.side*(1-Math.max(0,Math.min(1,state.clearance/190)))*1.05}let error=window.realTrainer.wrap(goalError+avoid),base=48-Math.min(24,Math.abs(error)*18);if(nearest<85)base=Math.min(base,30);let turn=Math.max(-32,Math.min(32,error*34)),guide=[Math.max(10,Math.min(75,base+turn)),Math.max(10,Math.min(75,base-turn))],target=[learned[0]*10+guide[0]*.9,learned[1]*10+guide[1]*.9],alpha=.24;lastCommand.left+=alpha*(target[0]-lastCommand.left);lastCommand.right+=alpha*(target[1]-lastCommand.right);return[Math.round(lastCommand.left),Math.round(lastCommand.right),error]}
function runPolicy(){if(!lastPose)return;if(performance.now()-lastPose.at>350){lastPose=null;lastCommand={left:0,right:0};stopCube();clearCubeLight();$("#deviceState").textContent="POSITION TIMEOUT / STOPPED";recordTelemetry({status:"POSITION_TIMEOUT"});return}if(window.trainedPolicy&&window.realTrainer){let point=matToSim(lastPose.x,lastPose.y),agent={x:point.x,y:point.y,angle:matAngleToSim(lastPose.a)};if(!isInsideRealCourse(agent)){lastCommand={left:0,right:0};stopCube();setCubeLight(255,0,0,80);$("#deviceState").textContent="COURSE EDGE / STOPPED";recordTelemetry({status:"COURSE_EDGE",x:lastPose.x,y:lastPose.y,angle:lastPose.a});clearInterval(policyTimer);flushTelemetry();return}let inputs=window.realTrainer.inputs(agent),learned=window.realTrainer.infer(window.trainedPolicy,inputs),[left,right,error]=guidedMotors(agent,learned);left=scaleRealMotor(left);right=scaleRealMotor(right);if(Math.hypot(825-agent.x,90-agent.y)<30){lastCommand={left:0,right:0};stopCube();setCubeLight(0,255,40,200);$("#deviceState").textContent="GOAL REACHED";recordTelemetry({status:"GOAL_REACHED",x:lastPose.x,y:lastPose.y,angle:lastPose.a});clearInterval(policyTimer);flushTelemetry();return}drive(left,right);let turn=Math.round(error*180/Math.PI),status=`P:${lastPose.x},${lastPose.y} A:${lastPose.a}° TURN:${turn}° L:${left} R:${right}`;$("#deviceState").textContent=status;recordTelemetry({status:"RUNNING",x:lastPose.x,y:lastPose.y,angle:lastPose.a,turn,left,right,course:currentLayout});return}stopCube();$("#deviceState").textContent="NO TRAINED POLICY"}
async function startPolicy(){clearInterval(policyTimer);await clearCubeLight();await new Promise(resolve=>setTimeout(resolve,150));lastCommand={left:0,right:0};avoidance={index:-1,side:0};let current=await idSensor.readValue();onPosition({target:{value:current}});runPolicy();policyTimer=setInterval(runPolicy,100)}
$('#connect').onclick=async()=>{let b=$('#connect');try{b.disabled=true;if(cube&&cube.gatt.connected&&idSensor&&motor){await stopCube();await startPolicy();b.disabled=false;b.textContent='AI方策を再送信　↻';toast('学習済み方策を再送信しました');return}if(!navigator.bluetooth)throw new Error('このブラウザはWeb Bluetoothに対応していません');b.textContent='toioを検索しています…';cube=await navigator.bluetooth.requestDevice({filters:[{services:[TOIO_SERVICE]}],optionalServices:[TOIO_SERVICE]});cube.addEventListener('gattserverdisconnected',()=>{clearInterval(policyTimer);lastPose=null;lastCommand={left:0,right:0};$('#deviceState').textContent='DISCONNECTED';stopCube()});let server=await cube.gatt.connect(),service=await server.getPrimaryService(TOIO_SERVICE);[motor,idSensor,light,configuration]=await Promise.all([service.getCharacteristic(MOTOR_CHAR),service.getCharacteristic(ID_CHAR),service.getCharacteristic(LIGHT_CHAR),service.getCharacteristic(CONFIG_CHAR)]);await configuration.writeValueWithoutResponse(Uint8Array.of(0x18,0x00,0x02,0x00)).catch(()=>{});await idSensor.startNotifications();idSensor.addEventListener('characteristicvaluechanged',onPosition);await startPolicy();b.disabled=false;b.textContent='AI方策を再送信　↻';toast(`${cube.name||'toio'} に接続しました`)}catch(e){clearInterval(policyTimer);b.disabled=false;b.textContent='Bluetoothでtoioに接続　⌁';$('#deviceState').textContent='WAITING FOR DEVICE';toast(e.message||'接続をキャンセルしました')}};
addEventListener('beforeunload',stopCube);rewards();grid();chart(0);
