const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={speed:60,safety:75,goal:80,crash:70,step:1,elapsed:0,paused:false,session:1200,raf:0};
const keys=['speed','safety','goal','crash'],presets={speed:[95,25,70,25],safe:[35,100,75,100],balance:[60,75,80,70]};
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function grade(v){return v>82?'S':v>68?'A':v>48?'B':'C'}
function rewards(){keys.forEach(k=>{let e=$('#'+k),v=+e.value;S[k]=v;e.style.setProperty('--fill',v+'%');$('#'+k+'O').textContent=(k==='crash'?'−':'+')+v});personality();radar()}
function personality(){let n,c,t;if(S.speed>80&&S.safety<50){n='フルスロットル・レーサー';c='最短・最速で駆け抜ける！ギリギリのラインも怖くないよ。';t='FULL THROTTLE RACER'}else if(S.safety>85&&S.speed<55){n='セーフティ・ガーディアン';c='急がなくても大丈夫。危険を予測して、確実な道を選ぶよ。';t='SAFETY GUARDIAN'}else if(S.goal<35){n='好奇心旺盛な探検家';c='ゴールだけが答えじゃない。まだ見ぬルートを探してみたい！';t='CURIOUS EXPLORER'}else{n='スマート・ナビゲーター';c='速さと安全、どっちも大切。最短ルートを冷静に探すよ！';t='SMART NAVIGATOR'}$('#pname').textContent=n;$('#comment').textContent=c;$('#btype').textContent=t;$('#g1').textContent=grade((S.goal+S.safety)/2);$('#g2').textContent=grade(S.speed-S.crash*.2+30);$('#g3').textContent=grade((S.safety+S.crash)/2)}
function radar(){let c=$('#radar'),x=c.getContext('2d'),cx=240,cy=155,R=103,v=[S.speed,S.goal,S.safety,S.crash,(S.goal+S.speed)/2],names=['スピード','目的意識','回避力','慎重さ','判断力'];x.clearRect(0,0,480,300);for(let r=1;r<=4;r++){x.beginPath();for(let i=0;i<5;i++){let a=-Math.PI/2+i*Math.PI*2/5,q=R*r/4;x[i?'lineTo':'moveTo'](cx+Math.cos(a)*q,cy+Math.sin(a)*q)}x.closePath();x.strokeStyle='#294354';x.stroke()}for(let i=0;i<5;i++){let a=-Math.PI/2+i*Math.PI*2/5;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='#1c3546';x.stroke();x.fillStyle='#7890a2';x.font='11px sans-serif';x.textAlign=i===0?'center':i<3?'left':'right';x.fillText(names[i],cx+Math.cos(a)*(R+22),cy+Math.sin(a)*(R+15))}x.beginPath();v.forEach((q,i)=>{let a=-Math.PI/2+i*Math.PI*2/5,q2=R*q/100;x[i?'lineTo':'moveTo'](cx+Math.cos(a)*q2,cy+Math.sin(a)*q2)});x.closePath();x.fillStyle='#18d9dc33';x.fill();x.strokeStyle='#18d9dc';x.lineWidth=2;x.stroke()}
function go(n){S.step=Math.max(S.step,n);$$('.panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===n));$$('.step').forEach(b=>b.classList.toggle('active',+b.dataset.step===n));scrollTo({top:0,behavior:'smooth'});if(n===2)startTraining()}
keys.forEach(k=>$('#'+k).oninput=()=>{$$('[data-preset]').forEach(b=>b.classList.remove('on'));rewards()});$$('[data-preset]').forEach(b=>b.onclick=()=>{presets[b.dataset.preset].forEach((v,i)=>$('#'+keys[i]).value=v);$$('[data-preset]').forEach(q=>q.classList.toggle('on',q===b));rewards()});
$('#reset').onclick=()=>{$('[data-preset=balance]').click();toast('初期設定に戻しました')};$('#start').onclick=()=>{$('#hero').classList.add('hidden');$('#app').classList.remove('hidden');radar()};$('#train').onclick=()=>go(2);$('#transfer').onclick=()=>go(3);$$('.step').forEach(b=>b.onclick=()=>{if(+b.dataset.step<=S.step)go(+b.dataset.step)});$('#sound').onclick=()=>toast('サウンドを切り替えました');
setInterval(()=>{if(!$('#app').classList.contains('hidden')&&S.session){S.session--;$('#time').textContent=`${String(S.session/60|0).padStart(2,'0')}:${String(S.session%60).padStart(2,'0')}`}},1000);
const sim=$('#sim'),ctx=sim.getContext('2d'),obs=[{x:270,y:125,r:34},{x:455,y:350,r:42},{x:650,y:170,r:38},{x:710,y:390,r:26}];let last=0;
function grid(){ctx.fillStyle='#07141f';ctx.fillRect(0,0,900,520);ctx.strokeStyle='#153044';for(let q=0;q<900;q+=45){ctx.beginPath();ctx.moveTo(q,0);ctx.lineTo(q,520);ctx.stroke()}for(let q=0;q<520;q+=45){ctx.beginPath();ctx.moveTo(0,q);ctx.lineTo(900,q);ctx.stroke()}ctx.setLineDash([5,7]);ctx.strokeStyle='#2a475a';ctx.strokeRect(32,28,836,464);ctx.setLineDash([])}
function bot(t,i){let p=(t*.15+i*.16)%1,x=65+p*760,y=390-p*255,learn=Math.min(1,S.elapsed/12),w=(1-learn)*80*Math.sin(p*19+i);obs.forEach(o=>{let d=x-o.x;if(Math.abs(d)<85)y+=(y>o.y?1:-1)*(o.r+38)*(85-Math.abs(d))/85*learn});return{x,y:y+w}}
function chart(r){let c=$('#chart'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#183244';for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,i*h/4);x.lineTo(w,i*h/4);x.stroke()}x.beginPath();for(let i=0;i<=100*r;i++){let px=i/100*w,py=h-15-i/100*(h-30)+Math.sin(i*.5)*7*(1-i/120);x[i?'lineTo':'moveTo'](px,py)}x.strokeStyle='#18d9dc';x.lineWidth=3;x.stroke()}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!S.paused)S.elapsed=Math.min(15,S.elapsed+dt);grid();ctx.beginPath();ctx.arc(825,90,35,0,7);ctx.fillStyle='#8465ff33';ctx.fill();ctx.strokeStyle='#8d70ff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#c7bbff';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText('GOAL',825,95);obs.forEach(o=>{ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fillStyle='#ff8b4828';ctx.fill();ctx.strokeStyle='#ff8b48';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffb17f';ctx.font='9px sans-serif';ctx.fillText('OBSTACLE',o.x,o.y+3)});let bots=Math.min(18,3+Math.floor(S.elapsed));for(let i=0;i<bots;i++){let p=bot(S.elapsed+i*.08,i);ctx.beginPath();ctx.arc(p.x,p.y,9,0,7);ctx.fillStyle=`rgba(24,217,220,${.15+i/bots*.75})`;ctx.fill();if(i===bots-1){ctx.strokeStyle='#c5ffff';ctx.lineWidth=3;ctx.stroke()}}let r=S.elapsed/15,tr=Math.floor(r*30000),rw=Math.round(-24+r*117),logs=['環境をスキャン中…','障害物との距離を学習中','衝突ルートを記憶しました','安全な迂回ルートを発見！','速度と回避のバランスを調整','ゴール到達率が80%を突破','最適なポリシーに収束しました ✓'];$('#count').textContent=(15-S.elapsed).toFixed(1);$('#trials').textContent=tr.toLocaleString();$('#success').textContent=Math.round(4+r*91)+'%';$('#crashes').textContent=Math.floor((1-r*.62)*tr/43).toLocaleString();$('#ring').style.background=`conic-gradient(var(--cyan) ${r*100}%,#1b3243 0)`;$('#reward').textContent=(rw>0?'+':'')+rw;$('#log').textContent=logs[Math.min(6,Math.floor(r*7))];chart(r);if(S.elapsed>=15){$('#transfer').classList.remove('hidden');S.step=3;toast('30,000回の学習が完了しました！');return}S.raf=requestAnimationFrame(frame)}
function startTraining(){cancelAnimationFrame(S.raf);S.elapsed=0;S.paused=false;$('#transfer').classList.add('hidden');last=performance.now();S.raf=requestAnimationFrame(frame)}$('#pause').onclick=()=>{S.paused=!S.paused;$('#pause').textContent=S.paused?'▶':'Ⅱ'};$('#retry').onclick=startTraining;

// toio BLE: official service, ID sensor and motor characteristics.
const TOIO_SERVICE='10b20100-5b3b-4571-9508-cf3efcd7bbae',ID_CHAR='10b20101-5b3b-4571-9508-cf3efcd7bbae',MOTOR_CHAR='10b20102-5b3b-4571-9508-cf3efcd7bbae';let cube=null,motor=null,idSensor=null,policyTimer=null,lastPose=null;
async function stopCube(){if(motor)await motor.writeValueWithoutResponse(Uint8Array.of(1,1,1,0,2,1,0)).catch(()=>{})}
function drive(left,right,duration=10){if(!motor)return;let ld=left>=0?1:2,rd=right>=0?1:2;motor.writeValueWithoutResponse(Uint8Array.of(2,1,ld,Math.min(115,Math.abs(left)),2,rd,Math.min(115,Math.abs(right)),duration)).catch(()=>{})}
function onPosition(e){let d=e.target.value;if(d.byteLength<7||d.getUint8(0)!==1)return;lastPose={x:d.getUint16(1,true),y:d.getUint16(3,true),a:d.getUint16(5,true)};runPolicy()}
function runPolicy(){if(!lastPose)return;let goal={x:430,y:250},dx=goal.x-lastPose.x,dy=goal.y-lastPose.y,dist=Math.hypot(dx,dy);if(dist<22){stopCube();$('#deviceState').textContent='GOAL REACHED';return}let target=(Math.atan2(dy,dx)*180/Math.PI+360)%360,error=((target-lastPose.a+540)%360)-180,base=25+S.speed*.55,turn=Math.max(-55,Math.min(55,error*(.55+S.safety/300)));drive(Math.round(base-turn),Math.round(base+turn),8)}
$('#connect').onclick=async()=>{let b=$('#connect');try{if(!navigator.bluetooth)throw new Error('このブラウザはWeb Bluetoothに対応していません');b.disabled=true;b.textContent='toioを検索しています…';cube=await navigator.bluetooth.requestDevice({filters:[{services:[TOIO_SERVICE]}],optionalServices:[TOIO_SERVICE]});cube.addEventListener('gattserverdisconnected',()=>{$('#deviceState').textContent='DISCONNECTED';stopCube()});let server=await cube.gatt.connect(),service=await server.getPrimaryService(TOIO_SERVICE);[motor,idSensor]=await Promise.all([service.getCharacteristic(MOTOR_CHAR),service.getCharacteristic(ID_CHAR)]);await idSensor.startNotifications();idSensor.addEventListener('characteristicvaluechanged',onPosition);$('#deviceState').textContent='CONNECTED / POLICY ACTIVE';b.textContent='AI方策を実行中';toast(`${cube.name||'toio'} に接続しました`);setTimeout(()=>$('#complete').classList.remove('hidden'),1400)}catch(e){b.disabled=false;b.textContent='Bluetoothでtoioに接続　⌁';$('#deviceState').textContent='WAITING FOR DEVICE';toast(e.message||'接続をキャンセルしました')}};
addEventListener('beforeunload',stopCube);rewards();grid();chart(0);
